# Generated by Django 6.1.1 on 2026-10-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('phone', 'phone Number/Mobile Money'), ('url', 'Website Link'), ('email', 'Email Address'), ('name', 'Individual / Business Name')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('clear', 'Clear'), ('suspicious', 'Suspicious'), ('flagged', 'Flagged')], default='clear', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scam_category', models.CharField(choices=[('momo', 'Fake Mobile Money Deposit / Request'), ('market', 'Facebook / Online Marketplace Fraud'), ('job', 'Fake Job Recruitment / Visa Scam'), ('loan', 'Rogue Online Loan App / Fee Scam'), ('other', 'Other Fraudulent Activity')], max_length=50)),
                ('description', models.TextField(help_text='Describe how the scam happened to warn others.')),
                ('evidence_image', models.ImageField(blank=True, help_text='Optional screenshot proof.', null=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scams.scamentity')),
            ],
        ),
    ]
